Genre.create(name: 'Art/ Architecture')
Genre.create(name: 'Autobiography')
Genre.create(name: 'Biography')
Genre.create(name: 'Children')
Genre.create(name: 'Classical Fiction')
Genre.create(name: 'Comic Book')
Genre.create(name: 'Cook Book')
Genre.create(name: 'Dystopian Fiction')
Genre.create(name: 'Fantasy')
Genre.create(name: 'Fiction')
Genre.create(name: 'Futurism')
Genre.create(name: 'Historical Fiction')
Genre.create(name: 'Historical Non-Fiction')
Genre.create(name: 'Horror')
Genre.create(name: 'Humor')
Genre.create(name: 'Magical Realism')
Genre.create(name: 'Memoir')
Genre.create(name: 'Mystery')
Genre.create(name: 'Non-Fiction')
Genre.create(name: 'Philosophy')
Genre.create(name: 'Photography')
Genre.create(name: 'Poetry')
Genre.create(name: 'Postmodern Fiction')
Genre.create(name: 'Religion/ Spirituality')
Genre.create(name: 'Romance')
Genre.create(name: 'Science Fiction')
Genre.create(name: 'Self Help')
Genre.create(name: 'Short Story')
Genre.create(name: 'Social Justice')
Genre.create(name: 'Space Opera')
Genre.create(name: 'Thriller')
Genre.create(name: 'Western')
Genre.create(name: 'Young Adult')